### ISSUE TITLE
Upload education data

### ISSUE THREAD

**Issue by kimberly-hu** [kimberly-hu/eco395m-midterm-project#2]
Can you upload the education data and any documentation explaining the variables? Thanks!

**Comment by yzliu123** [comment]
uploaded education data.
Please start with education_data summary, which provide an overview of the datasets, thanks!

**Comment by kimberly-hu** [comment]
Hi Lydia, 

It seems that you have uploaded the files to the top of the repo instead of the data folder. Could you create a subfolder "education" under "Data", and upload the education data there? 

Thanks!

Kimberly

**Comment by yzliu123** [comment]
Hi Kimberly,

Thanks for your reminder. I've relocated education data to "Data" folder.

Best,
Lydia
