### ISSUE TITLE
Education Data Merge: Student Academic Performance Variables

### ISSUE THREAD

**Issue by yzliu123** [kimberly-hu/eco395m-midterm-project#6]
Hi Kimberly,

In terms of the Academic Data, there are a lot of variables divided by races/ ethnicity. But we only need academic performance for all students. Can you please keep only the following 4: 

CDA00AA11219R	Campus 2019 Domain 1A: Meets Grade Level STD, All Students, EOC Algebra I Rate
CDA00ABI1219R	Campus 2019 Domain 1A: Meets Grade Level STD, All Students, EOC Biology Rate
CDA00AR11219R	Campus 2019 Domain 1A: Meets Grade Level STD, All Students, EOC English I Rate
CDA00AUS1219R	Campus 2019 Domain 1A: Meets Grade Level STD, All Students, EOC US History Rate

Thanks!

Lydia

**Comment by kimberly-hu** [comment]
Noted. Thanks!
